version: "3"

services:
  backend:
    container_name: be
    build: ./backend
    restart: 'no'
    ports:
      - 5000:5000
    expose:
      - 5000
    environment:
      APP_PORT: 5000
    networks:
      - golden-gate

  frontend:
    container_name: fe
    build: ./frontend
    restart: 'no'
    ports:
      - 80:80
    expose:
      - 80
    environment:
      REACT_APP_BE_PORT: 5000
      REACT_APP_BE_HOST: backend
    depends_on:
      - backend
    networks:
      - golden-gate

networks:
  golden-gate:
    driver: bridge
